### ISSUE TITLE
This repository is moving

### ISSUE THREAD

**Issue by zkoppert** [lingrino/go-fault#42]
# This repository is moving!!!
## Why?

The maintainer is no longer at GitHub and has requested this repo be moved to their account. https://github.com/lingrino

## When?

There is no specific date, but it will be before the end of May 2023.

## What will happen?

The repository will be moved to the new organisation at https://github.com/lingrino/go-fault (there's nothing there right now).

All current external contributors will retain their access.

All PRs should automatically rebase to the new repository location so you shouldn't need to do anything. If they don't please open an issue and I'll try sort things out.

All issues and discussions will be moved across at the same time too.

We will fork this repo after it is transferred back into the github organization in an attempt to not break builds that depend on this go package.

This will also be posted and pinned in the Discussions.

**Comment by lingrino** [comment]
Thank you!
